behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: False
      num_layers: 3
      hidden_units: 256
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1
        gamma: 0.95
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 100
    summary_freq: 10000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change: 100000

